### ISSUE TITLE
Task 2: Figure Out Tech Stack

### ISSUE THREAD

**Issue by smalinow** [JohnTantillo/OH-Helper#13]
● Links to website(s) containing documentation and how-tos for all of the 
language and libraries

● “Hello world” written in that language AND another program that results in the display of a simple window or webpage;

● (For web projects or projects needing a central server) links to website(s) showing how to get the language working in a Docker container;

● A brief explanation of why you will not need any other languages or libraries to get the work done.

**Comment by abhijittub** [comment]
**Languages** - Python [https://docs.python.org/3/](url), Scala [https://docs.scala-lang.org/](url)
