### ISSUE TITLE
As a TA, I want the highest priority questions first, so the queue is weighted by priority

### ISSUE THREAD

**Issue by johndunaske** [JohnTantillo/OH-Helper#7]

**Comment by FoolHardySorcerer** [comment]
***Acceptance Tests***
*Test 1*
1) Login to the application as a TA/Course Staff
2) Set the priority order of the questions with question 1 first (highest priority), question 2 second (middle priority), question 3 third (lowest priority)
3) Add 1 student with  question 1
3) Add 1 student with question 3
4)Confirm the student with question 1 is below question 3
5) Add 1 student with question 2
6)Confirm that the order of the queue is student with question 1, student with question 2, student with question 3

**Test 2**
1) Login to the application as a TA/Course Staff
2) Set the priority order of the questions with question 1 first (highest priority), question 2 second (middle priority), question 3 third (lowest priority)
3) Create a queue with student A with question 1, student B with question 2, student 3 with question 3.
4) Confirm the order of the queue in descending order (highest priority to lowest) is student A, Student B, Student C.
5) Change the priority with question 3 being highest and question 1 being lowest (priority of question 2 remains the same).
6)4) Confirm the order of the queue in descending order (highest priority to lowest) is student C, Student B, Student A.
